### ISSUE TITLE
Can't compile NDK for 32Bit in debug mode: undefined reference to 'sigemptyset' and 'sigaddset'

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#2136]
- Steps to reproduce:
  Run `./ndk-make.sh armeabi-v7a` or `./ndk-make.sh x86`
- Output:
```
Fast, partial, slow debug build. DO NOT UPLOAD THE APK ANYWHERE.
-- cross compiling to i686-linux-android (x86) --
    Finished dev [unoptimized] target(s) in 0.29s
-- ndk-build --
Android NDK: WARNING: APP_PLATFORM android-16 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-16. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
[x86] Compile++      : native-utils <= org_thoughtcrime_securesms_util_FileUtils.cpp
[x86] Compile        : native-utils <= dc_wrapper.c
[x86] SharedLibrary  : libnative-utils.so
jni/x86/libdeltachat.a(signal_hook-2530526319fba6eb.signal_hook.br2krarz-cgu.6.rcgu.o):signal_hook.br2krarz-cgu.6:function signal_hook::low_level::signal_details::emulate_default_handler::h0c9c85f8b16d90b7: error: undefined reference to 'sigemptyset'
jni/x86/libdeltachat.a(signal_hook-2530526319fba6eb.signal_hook.br2krarz-cgu.6.rcgu.o):signal_hook.br2krarz-cgu.6:function signal_hook::low_level::signal_details::emulate_default_handler::h0c9c85f8b16d90b7: error: undefined reference to 'sigaddset'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/x86/libnative-utils.so] Error 1
```

In release mode (when I just run `ndk_make.sh`) everything works fine.

Do y'all also have this problem?

@link2xt do you have any idea why this might have happened?

**Comment by link2xt** [comment]
Looks like it is broken since https://github.com/vorner/signal-hook/commit/b46473ff95f78cc9e0ae1d31afa2923102509091

Old Android (API 16 is used for `armeabi-v7a` and `x86`) did not support `sigaddset`/`sigemptyset`. `signal-hook` should exclude the code somehow in this case, like they do for Windows.

The reason it does not fail in release mode is because LTO (link-time optimization) enabled by `CARGO_PROFILE_RELEASE_LTO=on` eliminates the code calling `sigaddset` / `sigemptyset` before the linker has a chance to fail.

**Comment by Hocuri** [comment]
I created an issue: https://github.com/vorner/signal-hook/issues/118

**Comment by link2xt** [comment]
You also need to replace 16 with 21 manually in `jni/Application.mk`, first line always says `APP_PLATFORM := android-16`.

**Comment by Hocuri** [comment]
Ah yes, with `APP_PLATFORM := android-21` it compiles, thanks!

**Comment by Hocuri** [comment]
I'll add the android4 label, as this only is a problem because we are targeting android4.

I completed the PR at https://github.com/vorner/signal-hook/pull/121, however I noticed that when compiling for `x86` then there is another error line which I had overlooked before, and linking still fails :/

    jni/x86/libdeltachat.a(sqlite3.o):sqlite3.c:aSyscall: error: undefined reference to 'mmap64'

**Comment by Hocuri** [comment]
https://github.com/vorner/signal-hook/issues/118 was fixed

**Comment by Hocuri** [comment]
I was just going to open an issue for the sqlite problem when I noticed it disappeared :tada: Seems like Sqlite fixed it by themselves
